# Generated by Django 4.2.6 on 2023-10-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_post_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='avatar',
            new_name='img_avatar',
        ),
    ]
