# Generated by Django 4.2.6 on 2023-10-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_avatar_post_img_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_avatar',
            new_name='Image',
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
